### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by rbracco** [nstory/collection_boxes#1]
Hey Nathan, first, thank you for doing this. I had the same idea and when trying to find a way to detect the removal of collection boxes, I came across your excellent site mailboxlocate.com, which after some googling, eventually got me here. 

Is there anything you need as far as support? My background is in data science and machine learning, but I'm also experienced with javascript and leafletjs. I have started a fork that will be focused on analysis of the data in Python using Pandas and other tools, but would be happy to move it in to a separate folder or branch of this repo if you think that would work better. Thanks again and please let me know how I can contribute.

**Comment by nstory** [comment]
Hey there!

So, I'm collecting the collection box data, and I intend to update this repo as more data comes in. I set up a job to regularly scrape new data from the USPS site.

I just added [a table showing the change in collection boxes by state](https://github.com/nstory/collection_boxes#2019-to-2020-added-and-removed) which I think is cool -- but, realistically, I don't have the background in data science and the related analysis and visualization tools to do detailed analysis of this data.

If you're interested in that work, I think the best thing to do would be for you to create a separate repo with your code, results, etc. and I can link to that repo from the README in this one, along with any other projects people create with this data. I would love to hear about anything you create!

**Comment by rbracco** [comment]
Awesome, the table looks great. I'd be happy to maintain a repo for analyzing/visualizing the data and try to pull in other developers, and we can keep this one for holding the original data, scrapers, and diffs. I'll let you know if I come up with anything useful.
