### ISSUE TITLE
Quickly Obtain Past Records via USPS FOIA Reading Room

### ISSUE THREAD

**Issue by rbracco** [nstory/collection_boxes#3]
I discovered the USPS has a [FOIA Reading Room](https://pfoiapal.usps.com/app/ReadingRoom.aspx) that allows the public to view frequently requested records. Here are [Tips for searching](https://pfoiapal.usps.com/app/SearchTips.aspx). I tried briefly but all of my searches came back empty, even for incredibly broad search terms like "mail". I didn't have time to dig into the Search Tips, but I will return later and try to figure it out and post an update.

**Comment by nstory** [comment]
Ohhh, I remember playing with that last year based on a similar thought process. I couldn't get it to work 🤷‍♂️  I always got empty results just like you observed

**Comment by rbracco** [comment]
I believe I found the documents here: https://about.usps.com/who/legal/foia/library.htm, but it doesn't look like there's anything of interest. It may be possible to access more through the reading room but I can't figure it out. Closing the issue for now.
